version: "3.8"
services:
  vueapp:
    build: ./frontend
    container_name: reorganize_vue3
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ "npm", "run", "serve" ]

networks:
  host:
    driver: host
